/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin.
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: generate_date
 */
package nckd.yanye.fi.common;

import java.util.HashMap;
import java.util.Map;

/**
 * cloudflg云appflg应用-通用常量类<br>
 * 代码中不能存在硬编码敏感信息，如账号、密码、http外链、ftp外链、邮箱等。<br>
 * 标识或缓存的常量，需以"KEY_"、"FID_"、"ENTRY_"或"SUBENTRY_"作为变量的前缀。<br>
 *
 * @author devflg
 * @date generate_date
 */
public class AppflgConstant {

	public static final String KEY_APP_NAME = "cloudflg-appflg";


	public static final Map<String,String> KEY_MAP = new HashMap<>(6);

	public static final Map<String, String> getMap() {
		KEY_MAP.put("01","安全生产设备");
		KEY_MAP.put("02","环保设备");
		KEY_MAP.put("03","电子专用设备");
		KEY_MAP.put("04","检测设备");
		KEY_MAP.put("05","专用仪器仪表");
		KEY_MAP.put("06","非专用设备");
		return KEY_MAP;
	}

	public static final Map<String,String> KEY_RESDEVDEVICEMap = new HashMap<>(2);

	public static final Map<String, String> getResdevdeviceMap() {
		KEY_RESDEVDEVICEMap.put("0","否");
		KEY_RESDEVDEVICEMap.put("1","是");
		return KEY_RESDEVDEVICEMap;
	}
}
